server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/payment
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  doc:
    api-docs:
      path: /api-docs
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9092
      bindings:
        orderCreated-in-0:
          destination: 'streaming.order.created'
    application:
      name: payment-api